---

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - fence-virtd
  - fence-virtd-multicast
  - fence-virtd-libvirt

- name: systemctl enable fence_virtd
  service: name=fence_virtd enabled=yes state=started

- name: Install software
  yum: name={{ item }} state=present
  with_items:
[]

