---

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm


- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - update


- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - pcs
  - pacemaker
  - corosync
  - fence-agents-all
  - resource-agents
  - nfs-utils
  - ntp
  - ntpdate

- name: systemctl enable pcsd
  service: name=pcsd enabled=yes state=started
- name: systemctl disable firewalld
  service: name=firewalld enabled=no state=stopped
- name: systemctl enable ntpdate
  service: name=ntpdate enabled=yes state=started
- name: systemctl enable ntpd
  service: name=ntpd enabled=yes state=started
