---

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - pcs
  - pacemaker
  - corosync
  - fence-agents-all
  - resource-agents

- name: systemctl enable pcsd
  service: name=pcsd enabled=yes state=started
- name: systemctl disable firewalld
  service: name=firewalld enabled=no state=stopped
