---

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - nfs-utils

- name: systemctl enable nfs-server
  service: name=nfs-server enabled=yes state=started

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - haproxy

- name: systemctl enable haproxy
  service: name=haproxy enabled=yes state=started

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - bind

- name: systemctl enable named
  service: name=named enabled=yes state=started

- name: Install software
  yum: name={{ item }} state=present
  with_items:
  - dhcp

- name: systemctl enable dhcpd
  service: name=dhcpd enabled=yes state=started
